# Docker Compose configuration for development
version: '3.8'

services:
  gateway:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - GATEWAY_PORT=3000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - CACHE_ENABLED=true
      - CACHE_BACKEND=memory
      - LOG_LEVEL=debug
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
    networks:
      - gateway-dev-network
    command: npm run dev

  redis-dev:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    networks:
      - gateway-dev-network
    command: redis-server --appendonly yes

networks:
  gateway-dev-network:
    driver: bridge