# RBAC configuration for LLM Gateway
apiVersion: v1
kind: ServiceAccount
metadata:
  name: llm-gateway-sa
  namespace: llm-gateway
  labels:
    app: llm-gateway
    component: rbac

---
# Role for LLM Gateway service account
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: llm-gateway
  name: llm-gateway-role
  labels:
    app: llm-gateway
    component: rbac
rules:
# Allow reading ConfigMaps and Secrets
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
# Allow reading service information
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "list", "watch"]
# Allow reading pod information (for health checks)
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]

---
# RoleBinding to associate the role with the service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: llm-gateway-rolebinding
  namespace: llm-gateway
  labels:
    app: llm-gateway
    component: rbac
subjects:
- kind: ServiceAccount
  name: llm-gateway-sa
  namespace: llm-gateway
roleRef:
  kind: Role
  name: llm-gateway-role
  apiGroup: rbac.authorization.k8s.io