# Secret for API keys and sensitive configuration
apiVersion: v1
kind: Secret
metadata:
  name: llm-gateway-secrets
  namespace: llm-gateway
  labels:
    app: llm-gateway
    component: secrets
type: Opaque
stringData:
  # API Keys (replace with your actual keys)
  OPENAI_API_KEY: "your-openai-api-key-here"
  GEMINI_API_KEY: "your-gemini-api-key-here"
  
  # Redis password (if using authentication)
  REDIS_PASSWORD: ""
  
  # JWT secrets for authentication (if implemented)
  JWT_SECRET: "your-jwt-secret-here"
  
  # SSL/TLS certificate (if using HTTPS)
  SSL_CERT: ""
  SSL_KEY: ""