# Development environment configuration
server:
  port: 3000
  corsOrigins: ["http://localhost:3000", "http://localhost:3001"]

logging:
  level: "debug"
  format: "text"

cache:
  backend: "memory"
  ttl: 300  # 5 minutes for faster development

rateLimit:
  max: 1000  # Higher limit for development

providers:
  openai:
    timeout: 10000  # Shorter timeout for development
  gemini:
    baseUrl: "https://generativelanguage.googleapis.com/v1beta"
    timeout: 10000

metrics:
  enabled: false  # Disable metrics in development